### ISSUE TITLE
DSharpPlus example is outdated

### ISSUE THREAD

**Issue by Plootie** [lavalibs/Lavalink.NET#6]
The current DSharpPlus example uses a nuget package that no longer exists and cant be used on DSharpPlus 3.2.3 (latest stable ver)

**Comment by Kashalls** [comment]
Can ya fix it?

**Comment by Dev-Yukine** [comment]
DSharpPlus doesn't support third party module due to the decision of there devs, i will drop support for this library in the rewrite (which i will start soon) and no longer support it. You can use there first party module instead.
